#!/usr/bin/env sh

file="$PWD/package.json"

versionLine="$(grep '"version":' "$file")"

last_number=$(echo "$versionLine" | grep -o '[0-9]\+"' | sed 's/"$//')

new_number=$((last_number + 1))

new_line=$(echo "$versionLine" | sed "s/$last_number\"/$new_number\"/")

# Detect OS and adjust sed in-place editing command accordingly
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s|$versionLine|$new_line|" "$file"
else
  sed -i "s|$versionLine|$new_line|" "$file"
fi

git add .
